### PR TITLE
First draft proposal of support for Telos EOSIO chain

### PR DESCRIPTION
**Pull request by marlonwilliams**
Thanks again for your openness in reviewing this and commenting. You didn't have to take time out for this.

As you're aware, most of the heavy lifting is in the blockchain plugin. You'll notice that I used the eos.js plugin as a base and made the necessary changes that were obvious, resulting in redundant code in both eos.js and tlos.js that could use a little refactoring. Hope this isn't too cumbersome, but this is just a first draft based on my understanding of your codebase (which, by the way, is very well written and organized - kudos!)

### CODE REVIEW

**Comment by nsjames** [comment]
I have started work on a more dynamic branch for this which doesn't hard code any fork into Scatter as that is setting bad precedent ( forks should not be hardcoded into Scatter, as there may be many. ) Blockchain plugins are reserved for new **blockchains**, not forks of a blockchain so the `eos.js` plugin will need to be extended within itself to support forking behavior as opposed to adding a `tlos.js`.

Check out https://github.com/GetScatter/ScatterDesktop/tree/forks

I got stuck doing the key stuff since this: https://github.com/EOSIO/eosjs-ecc/pull/30 is not implemented yet. Will continue if that gets merged.

**Comment by marlonwilliams** [comment]
Thanks for your feedback and for taking a serious look at this. I'll take a look at the forks tree now.

thx again

**Comment by marlonwilliams** [comment]
Thanks for creating the "forks" branch to address this. It was a pleasure. 
Closing.

**Comment by marlonwilliams** [comment]
FYI @nsjames - pull request for EOSIO/eosjs-ecc#30 will be merged.

**Comment by nsjames** [comment]
Ping me when it's merged and pushed to npm :)

**Comment by marlonwilliams** [comment]
Released in eosjs@16.0.2 and eosjs-ecc@4.0.3 in npm. Thanks, Nathan!!

**Comment by nsjames** [comment]
72509aff5dfef05004a0ec33c544b15fc7646b47

**Pull request closed without merging**
